image: python:3.7

stages:
  - lint
  - unit_tests
  - integration_tests
  - build

before_script:
  - pip install poetry
  - poetry install

py_lint:
  stage: lint
  script:
    - poetry run black .

testing:
  stage: unit_tests
  script:
    - poetry run python -m unittest -v

integration:
  stage: initegration_tests
  script:
    - echo "Integration tests..."

building:
  stage: build
  only:
    - tags
  script:
    - poetry build
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN