image: python:3.7

stages:
  - test
  - lint
  - build

before_script:
  - pip install poetry
  - poetry install

testing:
  stage: test
  script:
    - poetry run python -m unittest -v

py_lint:
  stage: lint
  script:
    - poetry run black .

building:
  stage: build
  script:
    - poetry build
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN