repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: no-commit-to-branch
        args:
          - --branch
          - main
          - --branch
          - stg
          - --branch
          - lve
          - --branch
          - dev
          - --branch
          - cac
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length
          - "120"
          - --target-version
          - py310
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--line-length"
          - "120"
          - "--balanced"
          - "--use-parentheses"
  - repo: local
    hooks:
      - id: pyright
        name: Python Type Check
        description: Runs Pyright over python files
        entry: poetry run python -m pyright  # TODO: Use script so we can run per service?
        language: node
        types: [python]
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude_types:
          - yaml  # This is messing with my k8s templating
          - markdown  # this is messing with my gitlab tables
          - html # Exclude html templating too
        stages:
          - commit  # This randomly started failing in validating the commit message, idk
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.70.1
    hooks:
      - id: terraform_fmt
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
  - repo: https://github.com/myint/rstcheck
    rev: v5.0.0
    hooks:
      - id: rstcheck
  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.5.1
    hooks:
      - id: opa-fmt
  - repo: local
    hooks:
      - id: prepare-commit-message
        name: Prepare Commit Message
        language: system
        entry: python3 dev/tools/pre_commit_prepare_commit_message.py
        stages:
          - prepare-commit-msg
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check Valid Commit message
        language: system
        entry: python3 dev/tools/pre_commit_check_commit_message.py
        stages:
          - commit-msg
          - manual
default_language_version:
  python: python3
default_stages:
  - commit
